// Mocks generated by Mockito 5.4.2 from annotations
// in intheloopapp/test/ui/likes_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:intheloopapp/data/database_repository.dart' as _i3;
import 'package:intheloopapp/domains/models/activity.dart' as _i9;
import 'package:intheloopapp/domains/models/ai_model.dart' as _i14;
import 'package:intheloopapp/domains/models/avatar.dart' as _i15;
import 'package:intheloopapp/domains/models/badge.dart' as _i10;
import 'package:intheloopapp/domains/models/booking.dart' as _i11;
import 'package:intheloopapp/domains/models/comment.dart' as _i2;
import 'package:intheloopapp/domains/models/loop.dart' as _i8;
import 'package:intheloopapp/domains/models/option.dart' as _i6;
import 'package:intheloopapp/domains/models/review.dart' as _i13;
import 'package:intheloopapp/domains/models/service.dart' as _i12;
import 'package:intheloopapp/domains/models/user_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeComment_0 extends _i1.SmartFake implements _i2.Comment {
  _FakeComment_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseRepository extends _i1.Mock
    implements _i3.DatabaseRepository {
  MockDatabaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> userEmailExists(String? email) => (super.noSuchMethod(
        Invocation.method(
          #userEmailExists,
          [email],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<void> createUser(_i5.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i6.Option<_i5.UserModel>> getUserByUsername(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByUsername,
          [username],
        ),
        returnValue: _i4.Future<_i6.Option<_i5.UserModel>>.value(
            _i7.dummyValue<_i6.Option<_i5.UserModel>>(
          this,
          Invocation.method(
            #getUserByUsername,
            [username],
          ),
        )),
      ) as _i4.Future<_i6.Option<_i5.UserModel>>);
  @override
  _i4.Future<_i6.Option<_i5.UserModel>> getUserById(
    String? userId, {
    bool? ignoreCache = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
          {#ignoreCache: ignoreCache},
        ),
        returnValue: _i4.Future<_i6.Option<_i5.UserModel>>.value(
            _i7.dummyValue<_i6.Option<_i5.UserModel>>(
          this,
          Invocation.method(
            #getUserById,
            [userId],
            {#ignoreCache: ignoreCache},
          ),
        )),
      ) as _i4.Future<_i6.Option<_i5.UserModel>>);
  @override
  _i4.Future<List<_i5.UserModel>> searchUsersByLocation({
    required double? lat,
    required double? lng,
    int? radiusInMeters = 50000,
    int? limit = 100,
    String? lastUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsersByLocation,
          [],
          {
            #lat: lat,
            #lng: lng,
            #radiusInMeters: radiusInMeters,
            #limit: limit,
            #lastUserId: lastUserId,
          },
        ),
        returnValue: _i4.Future<List<_i5.UserModel>>.value(<_i5.UserModel>[]),
      ) as _i4.Future<List<_i5.UserModel>>);
  @override
  _i4.Future<void> updateUserData(_i5.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUserData,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<bool> checkUsernameAvailability(
    String? username,
    String? userid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkUsernameAvailability,
          [
            username,
            userid,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<List<_i5.UserModel>> getViewLeaders() => (super.noSuchMethod(
        Invocation.method(
          #getViewLeaders,
          [],
        ),
        returnValue: _i4.Future<List<_i5.UserModel>>.value(<_i5.UserModel>[]),
      ) as _i4.Future<List<_i5.UserModel>>);
  @override
  _i4.Future<List<_i5.UserModel>> getBookingLeaders() => (super.noSuchMethod(
        Invocation.method(
          #getBookingLeaders,
          [],
        ),
        returnValue: _i4.Future<List<_i5.UserModel>>.value(<_i5.UserModel>[]),
      ) as _i4.Future<List<_i5.UserModel>>);
  @override
  _i4.Future<List<_i5.UserModel>> getBookerLeaders() => (super.noSuchMethod(
        Invocation.method(
          #getBookerLeaders,
          [],
        ),
        returnValue: _i4.Future<List<_i5.UserModel>>.value(<_i5.UserModel>[]),
      ) as _i4.Future<List<_i5.UserModel>>);
  @override
  _i4.Future<_i6.Option<_i8.Loop>> getLoopById(
    String? loopId, {
    bool? ignoreCache = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLoopById,
          [loopId],
          {#ignoreCache: ignoreCache},
        ),
        returnValue: _i4.Future<_i6.Option<_i8.Loop>>.value(
            _i7.dummyValue<_i6.Option<_i8.Loop>>(
          this,
          Invocation.method(
            #getLoopById,
            [loopId],
            {#ignoreCache: ignoreCache},
          ),
        )),
      ) as _i4.Future<_i6.Option<_i8.Loop>>);
  @override
  _i4.Future<void> addLoop(_i8.Loop? loop) => (super.noSuchMethod(
        Invocation.method(
          #addLoop,
          [loop],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> deleteLoop(_i8.Loop? loop) => (super.noSuchMethod(
        Invocation.method(
          #deleteLoop,
          [loop],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<List<_i8.Loop>> getUserLoops(
    String? userId, {
    int? limit = 20,
    String? lastLoopId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLoops,
          [userId],
          {
            #limit: limit,
            #lastLoopId: lastLoopId,
          },
        ),
        returnValue: _i4.Future<List<_i8.Loop>>.value(<_i8.Loop>[]),
      ) as _i4.Future<List<_i8.Loop>>);
  @override
  _i4.Stream<_i8.Loop> userLoopsObserver(
    String? userId, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #userLoopsObserver,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i4.Stream<_i8.Loop>.empty(),
      ) as _i4.Stream<_i8.Loop>);
  @override
  _i4.Future<List<_i8.Loop>> getUserOpportunities(
    String? userId, {
    int? limit = 20,
    String? lastLoopId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserOpportunities,
          [userId],
          {
            #limit: limit,
            #lastLoopId: lastLoopId,
          },
        ),
        returnValue: _i4.Future<List<_i8.Loop>>.value(<_i8.Loop>[]),
      ) as _i4.Future<List<_i8.Loop>>);
  @override
  _i4.Stream<_i8.Loop> userOpportunitiesObserver(
    String? userId, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #userOpportunitiesObserver,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i4.Stream<_i8.Loop>.empty(),
      ) as _i4.Stream<_i8.Loop>);
  @override
  _i4.Future<List<_i8.Loop>> getFollowingLoops(
    String? currentUserId, {
    int? limit = 100,
    String? lastLoopId,
    bool? ignoreCache = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowingLoops,
          [currentUserId],
          {
            #limit: limit,
            #lastLoopId: lastLoopId,
            #ignoreCache: ignoreCache,
          },
        ),
        returnValue: _i4.Future<List<_i8.Loop>>.value(<_i8.Loop>[]),
      ) as _i4.Future<List<_i8.Loop>>);
  @override
  _i4.Stream<_i8.Loop> followingLoopsObserver(
    String? currentUserId, {
    int? limit = 100,
    bool? ignoreCache = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #followingLoopsObserver,
          [currentUserId],
          {
            #limit: limit,
            #ignoreCache: ignoreCache,
          },
        ),
        returnValue: _i4.Stream<_i8.Loop>.empty(),
      ) as _i4.Stream<_i8.Loop>);
  @override
  _i4.Future<List<_i8.Loop>> getAllLoops(
    String? currentUserId, {
    int? limit = 100,
    String? lastLoopId,
    bool? ignoreCache = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllLoops,
          [currentUserId],
          {
            #limit: limit,
            #lastLoopId: lastLoopId,
            #ignoreCache: ignoreCache,
          },
        ),
        returnValue: _i4.Future<List<_i8.Loop>>.value(<_i8.Loop>[]),
      ) as _i4.Future<List<_i8.Loop>>);
  @override
  _i4.Stream<_i8.Loop> allLoopsObserver(
    String? currentUserId, {
    int? limit = 100,
    bool? ignoreCache = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #allLoopsObserver,
          [currentUserId],
          {
            #limit: limit,
            #ignoreCache: ignoreCache,
          },
        ),
        returnValue: _i4.Stream<_i8.Loop>.empty(),
      ) as _i4.Stream<_i8.Loop>);
  @override
  _i4.Future<void> addLike(
    String? currentUserId,
    String? loopId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLike,
          [
            currentUserId,
            loopId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> deleteLike(
    String? currentUserId,
    String? loopId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLike,
          [
            currentUserId,
            loopId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<bool> isLiked(
    String? currentUserId,
    String? loopId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isLiked,
          [
            currentUserId,
            loopId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<List<_i5.UserModel>> getLikes(String? loopId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikes,
          [loopId],
        ),
        returnValue: _i4.Future<List<_i5.UserModel>>.value(<_i5.UserModel>[]),
      ) as _i4.Future<List<_i5.UserModel>>);
  @override
  _i4.Future<List<_i2.Comment>> getComments(
    String? rootId, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [rootId],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.Comment>>.value(<_i2.Comment>[]),
      ) as _i4.Future<List<_i2.Comment>>);
  @override
  _i4.Stream<_i2.Comment> commentsObserver(
    String? rootId, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #commentsObserver,
          [rootId],
          {#limit: limit},
        ),
        returnValue: _i4.Stream<_i2.Comment>.empty(),
      ) as _i4.Stream<_i2.Comment>);
  @override
  _i4.Future<_i2.Comment> getComment(
    String? rootId,
    String? commentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComment,
          [
            rootId,
            commentId,
          ],
        ),
        returnValue: _i4.Future<_i2.Comment>.value(_FakeComment_0(
          this,
          Invocation.method(
            #getComment,
            [
              rootId,
              commentId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Comment>);
  @override
  _i4.Future<void> addComment(_i2.Comment? comment) => (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [comment],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> likeComment(
    String? currentUserId,
    _i2.Comment? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #likeComment,
          [
            currentUserId,
            comment,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> unlikeComment(
    String? currentUserId,
    _i2.Comment? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlikeComment,
          [
            currentUserId,
            comment,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<bool> isCommentLiked(
    String? currentUserId,
    _i2.Comment? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isCommentLiked,
          [
            currentUserId,
            comment,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<void> shareLoop(_i8.Loop? loop) => (super.noSuchMethod(
        Invocation.method(
          #shareLoop,
          [loop],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> reportLoop({
    required String? reporterId,
    required _i8.Loop? loop,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportLoop,
          [],
          {
            #reporterId: reporterId,
            #loop: loop,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<int> followersNum(String? userid) => (super.noSuchMethod(
        Invocation.method(
          #followersNum,
          [userid],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
  @override
  _i4.Future<int> followingNum(String? userid) => (super.noSuchMethod(
        Invocation.method(
          #followingNum,
          [userid],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
  @override
  _i4.Future<void> followUser(
    String? currentUserId,
    String? visitedUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [
            currentUserId,
            visitedUserId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> unfollowUser(
    String? currentUserId,
    String? visitedUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [
            currentUserId,
            visitedUserId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<bool> isFollowingUser(
    String? currentUserId,
    String? visitedUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFollowingUser,
          [
            currentUserId,
            visitedUserId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<List<_i5.UserModel>> getFollowing(String? currentUserId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowing,
          [currentUserId],
        ),
        returnValue: _i4.Future<List<_i5.UserModel>>.value(<_i5.UserModel>[]),
      ) as _i4.Future<List<_i5.UserModel>>);
  @override
  _i4.Future<List<_i5.UserModel>> getFollowers(String? currentUserId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowers,
          [currentUserId],
        ),
        returnValue: _i4.Future<List<_i5.UserModel>>.value(<_i5.UserModel>[]),
      ) as _i4.Future<List<_i5.UserModel>>);
  @override
  _i4.Future<List<_i5.UserModel>> getCommonFollowers(
    String? currentUserID,
    String? observedUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonFollowers,
          [
            currentUserID,
            observedUserId,
          ],
        ),
        returnValue: _i4.Future<List<_i5.UserModel>>.value(<_i5.UserModel>[]),
      ) as _i4.Future<List<_i5.UserModel>>);
  @override
  _i4.Future<List<_i9.Activity>> getActivities(
    String? userId, {
    int? limit = 100,
    String? lastActivityId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivities,
          [userId],
          {
            #limit: limit,
            #lastActivityId: lastActivityId,
          },
        ),
        returnValue: _i4.Future<List<_i9.Activity>>.value(<_i9.Activity>[]),
      ) as _i4.Future<List<_i9.Activity>>);
  @override
  _i4.Stream<_i9.Activity> activitiesObserver(
    String? userId, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #activitiesObserver,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i4.Stream<_i9.Activity>.empty(),
      ) as _i4.Stream<_i9.Activity>);
  @override
  _i4.Future<void> addActivity({
    required String? currentUserId,
    required String? visitedUserId,
    required _i9.ActivityType? type,
    _i8.Loop? loop,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addActivity,
          [],
          {
            #currentUserId: currentUserId,
            #visitedUserId: visitedUserId,
            #type: type,
            #loop: loop,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> markActivityAsRead(_i9.Activity? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #markActivityAsRead,
          [activity],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<bool> isVerified(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #isVerified,
          [userId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<void> createBadge(_i10.Badge? badge) => (super.noSuchMethod(
        Invocation.method(
          #createBadge,
          [badge],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> sendBadge(
    String? badgeId,
    String? receiverId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendBadge,
          [
            badgeId,
            receiverId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Stream<_i10.Badge> userCreatedBadgesObserver(
    String? userId, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #userCreatedBadgesObserver,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i4.Stream<_i10.Badge>.empty(),
      ) as _i4.Stream<_i10.Badge>);
  @override
  _i4.Future<List<_i10.Badge>> getUserCreatedBadges(
    String? userId, {
    int? limit = 100,
    String? lastBadgeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCreatedBadges,
          [userId],
          {
            #limit: limit,
            #lastBadgeId: lastBadgeId,
          },
        ),
        returnValue: _i4.Future<List<_i10.Badge>>.value(<_i10.Badge>[]),
      ) as _i4.Future<List<_i10.Badge>>);
  @override
  _i4.Stream<_i10.Badge> userBadgesObserver(
    String? userId, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #userBadgesObserver,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i4.Stream<_i10.Badge>.empty(),
      ) as _i4.Stream<_i10.Badge>);
  @override
  _i4.Future<List<_i10.Badge>> getUserBadges(
    String? userId, {
    int? limit = 100,
    String? lastBadgeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserBadges,
          [userId],
          {
            #limit: limit,
            #lastBadgeId: lastBadgeId,
          },
        ),
        returnValue: _i4.Future<List<_i10.Badge>>.value(<_i10.Badge>[]),
      ) as _i4.Future<List<_i10.Badge>>);
  @override
  _i4.Future<void> createBooking(_i11.Booking? booking) => (super.noSuchMethod(
        Invocation.method(
          #createBooking,
          [booking],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i6.Option<_i11.Booking>> getBookingById(String? bookRequestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookingById,
          [bookRequestId],
        ),
        returnValue: _i4.Future<_i6.Option<_i11.Booking>>.value(
            _i7.dummyValue<_i6.Option<_i11.Booking>>(
          this,
          Invocation.method(
            #getBookingById,
            [bookRequestId],
          ),
        )),
      ) as _i4.Future<_i6.Option<_i11.Booking>>);
  @override
  _i4.Future<List<_i11.Booking>> getBookingsByRequesterRequestee(
    String? requesterId,
    String? requesteeId, {
    int? limit = 20,
    String? lastBookingRequestId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookingsByRequesterRequestee,
          [
            requesterId,
            requesteeId,
          ],
          {
            #limit: limit,
            #lastBookingRequestId: lastBookingRequestId,
          },
        ),
        returnValue: _i4.Future<List<_i11.Booking>>.value(<_i11.Booking>[]),
      ) as _i4.Future<List<_i11.Booking>>);
  @override
  _i4.Future<List<_i11.Booking>> getBookingsByRequester(
    String? userId, {
    int? limit = 20,
    String? lastBookingRequestId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookingsByRequester,
          [userId],
          {
            #limit: limit,
            #lastBookingRequestId: lastBookingRequestId,
          },
        ),
        returnValue: _i4.Future<List<_i11.Booking>>.value(<_i11.Booking>[]),
      ) as _i4.Future<List<_i11.Booking>>);
  @override
  _i4.Stream<_i11.Booking> getBookingsByRequesterObserver(
    String? userId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookingsByRequesterObserver,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i4.Stream<_i11.Booking>.empty(),
      ) as _i4.Stream<_i11.Booking>);
  @override
  _i4.Future<List<_i11.Booking>> getBookingsByRequestee(
    String? userId, {
    int? limit = 20,
    String? lastBookingRequestId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookingsByRequestee,
          [userId],
          {
            #limit: limit,
            #lastBookingRequestId: lastBookingRequestId,
          },
        ),
        returnValue: _i4.Future<List<_i11.Booking>>.value(<_i11.Booking>[]),
      ) as _i4.Future<List<_i11.Booking>>);
  @override
  _i4.Stream<_i11.Booking> getBookingsByRequesteeObserver(
    String? userId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookingsByRequesteeObserver,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i4.Stream<_i11.Booking>.empty(),
      ) as _i4.Stream<_i11.Booking>);
  @override
  _i4.Future<void> updateBooking(_i11.Booking? booking) => (super.noSuchMethod(
        Invocation.method(
          #updateBooking,
          [booking],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> createService(_i12.Service? service) => (super.noSuchMethod(
        Invocation.method(
          #createService,
          [service],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> updateService(_i12.Service? service) => (super.noSuchMethod(
        Invocation.method(
          #updateService,
          [service],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i6.Option<_i12.Service>> getServiceById(
    String? userId,
    String? serviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServiceById,
          [
            userId,
            serviceId,
          ],
        ),
        returnValue: _i4.Future<_i6.Option<_i12.Service>>.value(
            _i7.dummyValue<_i6.Option<_i12.Service>>(
          this,
          Invocation.method(
            #getServiceById,
            [
              userId,
              serviceId,
            ],
          ),
        )),
      ) as _i4.Future<_i6.Option<_i12.Service>>);
  @override
  _i4.Future<List<_i12.Service>> getUserServices(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserServices,
          [userId],
        ),
        returnValue: _i4.Future<List<_i12.Service>>.value(<_i12.Service>[]),
      ) as _i4.Future<List<_i12.Service>>);
  @override
  _i4.Future<void> deleteService(
    String? userId,
    String? serviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteService,
          [
            userId,
            serviceId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> showInterest({
    required String? userId,
    required String? loopId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showInterest,
          [],
          {
            #userId: userId,
            #loopId: loopId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> cancelInterest({
    required String? userId,
    required String? loopId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelInterest,
          [],
          {
            #userId: userId,
            #loopId: loopId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<List<_i5.UserModel>> getInterestedUsers(String? loopId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInterestedUsers,
          [loopId],
        ),
        returnValue: _i4.Future<List<_i5.UserModel>>.value(<_i5.UserModel>[]),
      ) as _i4.Future<List<_i5.UserModel>>);
  @override
  _i4.Future<bool> isInterested({
    required String? userId,
    required String? loopId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isInterested,
          [],
          {
            #userId: userId,
            #loopId: loopId,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<void> blockUser({
    required String? currentUserId,
    required String? blockedUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [],
          {
            #currentUserId: currentUserId,
            #blockedUserId: blockedUserId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> unblockUser({
    required String? currentUserId,
    required String? blockedUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [],
          {
            #currentUserId: currentUserId,
            #blockedUserId: blockedUserId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<bool> isBlocked({
    required String? currentUserId,
    required String? blockedUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isBlocked,
          [],
          {
            #currentUserId: currentUserId,
            #blockedUserId: blockedUserId,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<void> reportUser({
    required _i5.UserModel? reported,
    required _i5.UserModel? reporter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportUser,
          [],
          {
            #reported: reported,
            #reporter: reporter,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> createPerformerReview(_i13.PerformerReview? review) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPerformerReview,
          [review],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i6.Option<_i13.PerformerReview>> getPerformerReviewById({
    required String? revieweeId,
    required String? reviewId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPerformerReviewById,
          [],
          {
            #revieweeId: revieweeId,
            #reviewId: reviewId,
          },
        ),
        returnValue: _i4.Future<_i6.Option<_i13.PerformerReview>>.value(
            _i7.dummyValue<_i6.Option<_i13.PerformerReview>>(
          this,
          Invocation.method(
            #getPerformerReviewById,
            [],
            {
              #revieweeId: revieweeId,
              #reviewId: reviewId,
            },
          ),
        )),
      ) as _i4.Future<_i6.Option<_i13.PerformerReview>>);
  @override
  _i4.Future<List<_i13.PerformerReview>> getPerformerReviewsByPerformerId(
    String? performerId, {
    int? limit = 20,
    String? lastReviewId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPerformerReviewsByPerformerId,
          [performerId],
          {
            #limit: limit,
            #lastReviewId: lastReviewId,
          },
        ),
        returnValue: _i4.Future<List<_i13.PerformerReview>>.value(
            <_i13.PerformerReview>[]),
      ) as _i4.Future<List<_i13.PerformerReview>>);
  @override
  _i4.Stream<_i13.PerformerReview> getPerformerReviewsByPerformerIdObserver(
    String? performerId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPerformerReviewsByPerformerIdObserver,
          [performerId],
          {#limit: limit},
        ),
        returnValue: _i4.Stream<_i13.PerformerReview>.empty(),
      ) as _i4.Stream<_i13.PerformerReview>);
  @override
  _i4.Future<void> createBookerReview(_i13.BookerReview? review) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBookerReview,
          [review],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i6.Option<_i13.BookerReview>> getBookerReviewById({
    required String? revieweeId,
    required String? reviewId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookerReviewById,
          [],
          {
            #revieweeId: revieweeId,
            #reviewId: reviewId,
          },
        ),
        returnValue: _i4.Future<_i6.Option<_i13.BookerReview>>.value(
            _i7.dummyValue<_i6.Option<_i13.BookerReview>>(
          this,
          Invocation.method(
            #getBookerReviewById,
            [],
            {
              #revieweeId: revieweeId,
              #reviewId: reviewId,
            },
          ),
        )),
      ) as _i4.Future<_i6.Option<_i13.BookerReview>>);
  @override
  _i4.Future<List<_i13.BookerReview>> getBookerReviewsByBookerId(
    String? bookerId, {
    int? limit = 20,
    String? lastReviewId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookerReviewsByBookerId,
          [bookerId],
          {
            #limit: limit,
            #lastReviewId: lastReviewId,
          },
        ),
        returnValue:
            _i4.Future<List<_i13.BookerReview>>.value(<_i13.BookerReview>[]),
      ) as _i4.Future<List<_i13.BookerReview>>);
  @override
  _i4.Stream<_i13.BookerReview> getBookerReviewsByBookerIdObserver(
    String? bookerId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookerReviewsByBookerIdObserver,
          [bookerId],
          {#limit: limit},
        ),
        returnValue: _i4.Stream<_i13.BookerReview>.empty(),
      ) as _i4.Stream<_i13.BookerReview>);
  @override
  _i4.Future<_i14.AiImageModel?> getUserImageModel(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserImageModel,
          [userId],
        ),
        returnValue: _i4.Future<_i14.AiImageModel?>.value(),
      ) as _i4.Future<_i14.AiImageModel?>);
  @override
  _i4.Future<List<_i15.Avatar>> getUserAvatars(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserAvatars,
          [userId],
        ),
        returnValue: _i4.Future<List<_i15.Avatar>>.value(<_i15.Avatar>[]),
      ) as _i4.Future<List<_i15.Avatar>>);
  @override
  _i4.Stream<_i15.Avatar> userAvatarsObserver(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #userAvatarsObserver,
          [userId],
        ),
        returnValue: _i4.Stream<_i15.Avatar>.empty(),
      ) as _i4.Stream<_i15.Avatar>);
  @override
  _i4.Future<void> createAvatar(_i15.Avatar? avatar) => (super.noSuchMethod(
        Invocation.method(
          #createAvatar,
          [avatar],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
